apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-ingress-datacenter
  namespace: haproxy-controller-datacenter
  labels:
    run: haproxy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      serviceAccountName: haproxy-service-account-datacenter
      containers:
      - name: ingress-container-datacenter
        image: haproxytech/kubernetes-ingress
        args: [ "--default-backend-service=haproxy-controller-datacenter/service-backend-datacenter" ]
        resources:
          requests:
            cpu: "500m"
            memory: "50Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1024
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1024
        env:
        - name: TZ
          value: "Etc/UTC"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-service-datacenter
  namespace: haproxy-controller-datacenter
  labels:
    run: haproxy-ingress
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32456
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 32567
  - name: stat
    protocol: TCP
    port: 1024
    targetPort: 1024
    nodePort: 32678
  selector:
    run: haproxy-ingress
