apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: devops
spec:
  schedule: "*/6 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-devops
            image: httpd:latest
            args:
            - /bin/sh
            - -c
            - echo Welcome to xfusioncorp
          restartPolicy: OnFailure
