apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site-devops
  namespace: jekyll-namespace-devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
